eureka:
  instance:
    #将来注册到该注册中心的微服务包括注册中心都是用ip地址
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      #注册中心的ip地址
      defaultZone: http://192.168.157.134:8761/eureka/
spring:
  #数据库四要素
  datasource:
    url: jdbc:mysql://localhost/mysql
    password: ps123456
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  application:
    #微服务的名字
    name: userservice
server:
  port: 8882
